language: java
install: true

addons:
  sonarcloud:
    organization: "etat-de-geneve-github"
    token:
      secure: 2b3b12f9df9593d7276b3d219d1cecc5cb3025dd

jdk:
  - openjdk8

script:
# - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar
  - mvn clean package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
