language: java
install: true

addons:
  sonarcloud:
    organization: "etat-de-geneve-github"

jdk:
  - oraclejdk8

script:
  - mvn clean install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

